import React from 'react';
import { StyleSheet, Text, ScrollView, SafeAreaView, StatusBar } from 'react-native';
import InstructionPage from './InstructionPage';
import Button from '../General/Button';
import InstructionImage from './Instruction-2.png';

export default class Instruction1 extends React.Component {
  static navigationOptions = ({ navigation }) => {
    return {
      title: 'Instructions',
      headerLeft: (
        <Button
          onPress={() => navigation.goBack()}
          icon="chevron-left"
          isHeaderBack={true}
        />
      )
    }
  };

  render() {
    return (
      <InstructionPage 
      text="Enter the token generated by this App (the remote) into the control software and click begin. You should now recieve a notification on the remote, letting you know that you are ready to present."
      image={InstructionImage}
      next="Instruction3"
      navigation={this.props.navigation}
      />
    );
  }
}
